---
- name: Install kubernetes module
  pip:
    name: kubernetes

- name: Create namespace
  k8s:
    definition:
      kind: namespace
      apiVersion: v1
      metadata:
        name: "{{ app_namespace }}"
        
- name: Deploy app
  k8s:
    definition: "{{ lookup('template', 'deployment.yml') }}"
    namespace: "{{ app_namespace }}"