---
# Crear namespace en el que se añadiran los recursos
- name: Create namespace
  k8s:
    definition:
      kind: namespace
      apiVersion: v1
      metadata:
        name: "unir"

# Crear los deployments y servicios en el namespace creado
- name: Deploy app
  k8s:
    kubeconfig: "~/.kube/config"
    state: present
    src: roles/aks/template/deploy.yml
    namespace: "unir"
